url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "EARP Lab" # the name of your site, e.g. ACME Corp.
description: "Experimental Bioethics, AI, and Relational Moral Psychology Lab"
