menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}

people:
- {name: 'Brian Earp', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  bio: 'insert bio',
  image: 'assets/img/primary-investigator.jpg', url: '/1-brian'}
- {name: 'person 2', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  image: 'assets/img/primary-investigator.jpg', url: '/2-primary-investigator'}
- {name: 'person 3', 
  institution: 'Some University',  
  email: 'hello@university.edu', 
  image: 'assets/img/lab-technician.jpg', url: '/3-postdocs'}

PG: 
- {name: 'PG & UG Student', 
  institution: 'Some University', 
  image: 'assets/img/graduate-student.jpg'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
