menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}

people:
- {name: 'Brian Earp', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  bio: 'insert bio',
  image: 'assets/img/primary-investigator.jpg'}
- {name: 'person 2', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  bio: 'insert bio',
  image: 'assets/img/primary-investigator.jpg'}

postdoc:
- {name: 'postdoc name', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  bio: 'insert bio',
  image: 'assets/img/primary-investigator.jpg'}

student: 
- {name: 'student name', 
  institution: 'Some University', 
  email: 'hello@university.edu', 
  bio: 'insert bio',
  image: 'assets/img/primary-investigator.jpg'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
